### ISSUE TITLE
关于减少显存占用

### ISSUE THREAD

**Issue by 1145284121** [yihongXU/TransCenter#6]
感谢开源，
作者有试过输入小一点分辨率的图片，或者其他减少显存占用的思路，实验效果如何吗
（）当前的模型在batch_size调到1依然需要超过12G显存）

**Comment by yihongXU** [comment]
你好，我们没有试过减小输入分辨率。你可以尝试分辨率长宽减半。另外，我们将会在近期推出更轻便的版本，敬请期待，祝好。
